### ISSUE TITLE
grpc wrapper

### ISSUE THREAD

**Issue by watzon** [johnjansen/crystal-libraries-needed#88]
grpc is a rpc implementation by Google that's supposed to be very fast. It already has wrappers in several languages including Ruby and Python.

https://grpc.io

**Comment by jtianling** [comment]
need it too.

**Comment by Ray-Eldath** [comment]
eagerly waiting...

**Comment by alexanderadam** [comment]
If you are _very_ eager, you should rather consider writing an own shard (maybe using the [official Ruby implementation](https://github.com/grpc/grpc/tree/master/src/ruby) as help - you could probably even migrate most of the existing specs by using [Spectator](https://gitlab.com/arctic-fox/spectator) as a test framework).

Maybe other people waiting here will join you.

Otherwise it should be obvious that just adding "I'm waiting, too" comments won't bring _any_ benefit. You should rather use the ":+1:" button at the first comment for that.

**Comment by watzon** [comment]
I'm working on this right now. It'll probably take a bit since I'm writing out a whole parser for Google Protocol Buffers, but we'll see. I'll keep you posted.

**Comment by jgaskins** [comment]
Someone pointed me at this issue a while back and I completely forgot to comment on it. I've also been [working on a gRPC library](https://github.com/jgaskins/grpc) which includes its own basic implementation of HTTP/2 (just the parts needed for simple gRPC for now) and uses [this Protobuf shard](https://github.com/jeromegn/protobuf.cr) (of which I am also a maintainer) to serialize/deserialize messages.

**Comment by jgaskins** [comment]
I've updated the shard with a better readme and pushed [an example repo](https://github.com/jgaskins/grpc_example) to showcase how to use it. Hope this is helpful!

**Comment by alexanderadam** [comment]
Can't we close this issue then? :thinking:

**Comment by bcardiff** [comment]
cc: @Sija I think that you are the most active member listed in the contributors of this repo.
