### ISSUE TITLE
project - why are there so many dead libraries

### ISSUE THREAD

**Issue by ghost** [johnjansen/crystal-libraries-needed#90]
So I was browsing through the issues here, and most of the "promised" libraries created on GitHub just are empty....

**Comment by vladfaust** [comment]
It’s a ritorical question, I guess? 

Abandoning is usual in open source, because the attention is always switching. Developers have limited time and they need to earn money. Open source doesn’t bring money in short perspective, that’s why they have to do something else instead of writing open libraries. 

It’s a dream of mine to have enough money to live without working on commercial projects... I want to continue creating games, to write some protocols which would improve everybody’s lives. I want to finish my Crystal projects (core, prism) ar least!

But instead, I have to earn money doing another programming stuff...

**Comment by ghost** [comment]
@vladfaust Didn't looked from that perspective. I am a student, so I have kind of too much time.
